### ISSUE TITLE
Documentación APIs

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/the-gummy-bears#10]
algo como: 
- http://inegifacil.com/servicio-rest
- http://inegifacil.com/rest/indice/1002000001/i

**Comment by gabelula** [comment]
Genial! Les recomiendo crear un folder docs para documentación en este repo. Y luego usar readhtedocs.io para publicar la documentación. Es muy sencillo y hay hooks que se pueden hacer desde github para que la publicación sea automatica.
