### ISSUE TITLE
URLs dinámicas en cada proceso de contratación

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/the-gummy-bears#3]
Por ejemplo:
`contrato/OCDS-87SD3T-SEFIN-AD-SF-DRM-004-2015/#tender`
`contrato/OCDS-87SD3T-SEFIN-AD-SF-DRM-004-2015/#award-1`
`contrato/OCDS-87SD3T-SEFIN-AD-SF-DRM-004-2015/#contract-1`

**Comment by martinszy** [comment]
Hola, acabo de conocer el proyecto en IODC y estaba navegando un proceso de contratación y me encontré con este issue, qué bueno que ya lo tengan en vista, me parece importante para alguien que está intentando entender un proceso de compra y accede a los diferentes PDFs, porque al volver hacia atrás no se vuelve a la misma página en la que uno estaba.
