### ISSUE TITLE
Error en dependencia

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/the-gummy-bears#38]
como usuaria veo esto:

![image](https://cloud.githubusercontent.com/assets/2445854/15451616/a0b43460-1f91-11e6-9ba9-311d9e243074.png)

**Comment by elcoruco** [comment]
Como usuario que seleccionó un id válido, veo esto:

<img width="866" alt="screen shot 2016-05-22 at 12 27 30 pm" src="https://cloud.githubusercontent.com/assets/3756555/15455398/96fe9fb4-2018-11e6-9f77-504798678c87.png">

**Comment by elcoruco** [comment]
<img width="602" alt="screen shot 2016-05-22 at 12 40 59 pm" src="https://cloud.githubusercontent.com/assets/3756555/15455458/92ae93ea-201a-11e6-8b14-43ac467dfaa4.png">

Aunque solo tengo cierta sospecha de qué es lo que falla aquí, creo que primero hay que arreglar este "foreach" en resources/views/frontend/office.blade.php

lo que hace ahora, es regresar el último release del último contrato. (Si es exactamente eso lo que se quiere obtener, puedo escribir un mejor query). Pero si no, entonces el foreach debe terminar después de que obtiene la info de cada contrato, no solo del último.

**Comment by elcoruco** [comment]
<img width="777" alt="screen shot 2016-05-22 at 12 52 56 pm" src="https://cloud.githubusercontent.com/assets/3756555/15455528/4685641a-201c-11e6-99f5-21472c92a5e7.png">

aunque ahora que lo pienso, creo que mejor escribo desde cero este controller o____O
