### ISSUE TITLE
 Cambio: Cambios de Glosario. En amarillo se indican las frases que deben redirigir al hipervínculo entre paréntesis. El título de la sección también se indica en la primera oración. Modificación del texto de Suficiencia Presupuestal

### ISSUE THREAD

**Issue by acastedom** [GobiernoFacil/the-gummy-bears#52]
Título  cambia a:  “Términos Clave del Portal de Contrataciones Abiertas”
![image](https://cloud.githubusercontent.com/assets/19691136/15719086/eff770a4-27f3-11e6-942f-8f8be61f5948.png)

GOBIERNO ABIERTO
Aquél que colabora con sus ciudadanos para aprovechar las capacidades y conocimiento de diferentes sectores de la sociedad para mejorar la toma de decisiones en los procesos de diseño, elaboración, implementación y evaluación de políticas públicas, servicios públicos y programas gubernamentales, de forma abierta y transparente. De acuerdo con la Ley de para hacer de la Ciudad de México una Ciudad más Abierta (http://www.aldf.gob.mx/archivo-1b52054447d78a831c329f25931f03a5.pdf), para lograr esto se tienen ocho principios básicos: 

Transparencia: Garantizar que las acciones y decisiones sobre el uso de los recursos públicos sea del conocimiento de la población de manera accesible, y que promueva su reutilización y redistribución.
Participación: Promover la participación de la ciudadanía y la sociedad civil organizada para obtener su retroalimentación sobre la información que es publicada.
Colaboración: Promover las acciones que fomentan la corresponsabilidad entre el Gobierno y la sociedad.
Máxima Publicidad: Que toda la información que se define como pública,  se publique completa, de manera oportuna y accesible.
Usabilidad: Las herramientas gubernamentales deben comunicar la información de manera fácil y clara al usuario final o ciudadano. 
Innovación y Aprovechamiento de la Tecnología: La manera de interactuar y participar entre gobierno y la población procurarán ser innovadores, modernos y eficientes para fomentar la utilización de datos. 
Diseño que piensa en el Usuario: El diseño debe contemplar quién es el usuario final para que sea una herramienta fácil de usar con una experiencia satisfactoria para fomentar el uso de ella. 
Retroalimentación: Para promover la mejora e innovación en las acciones del Gobierno se debe promover el intercambio de conocimiento e información entre las personas y las instancias del propio Gobierno. 

Dentro de la misma línea, existe también la Ley de Transparencia, Acceso a la Información Pública y Rendición de Cuentas de la Ciudad de México (http://www.infodf.org.mx/documentospdf/Ley%20de%20Transparencia,%20Acceso%20a%20la%20Informaci%C3%B3n%20P%C3%BAblica%20y%20Rendici%C3%B3n%20de%20Cuentas%20de%20la%20Ciudad%20de%20M%C3%A9xico.pdf) que fomenta y defiende el derecho de todo ciudadano a ser informado y refuerza la obligación de las autoridades a proporcionar dicha información.

DATOS ABIERTOS GUBERNAMENTALES
Son los datos que se incluyen en el contrato, siempre y cuando no estén protegidos por la Ley de Protección de Datos Personales del Distrito Federal (http://www.aldf.gob.mx/archivo-f73bdb295c017416ad640607e8aa1275.pdf).

ASOCIACIÓN DE CONTRATACIONES ABIERTAS
La Asociación de Contrataciones Abiertas (http://www.open-contracting.org/) (Open Contracting Partnership, OCP por sus siglas en inglés) se fundó en 2012. Nace con el objetivo de incrementar la divulgación y la participación en todas las etapas de la contratación pública de los gobiernos. Su labor se centra en asegurar que los gobiernos sean eficaces y eficientes, que el sector privado crezca y prospere, y que los ciudadanos reciban los bienes y servicios que necesitan y merecen.

ESTÁNDAR DE DATOS DE CONTRATACIONES ABIERTAS
El Estándar de Datos de Contrataciones Abiertas (http://standard.open-contracting.org/latest/es/#) (Open Contracting Data Standard, OCDS por sus siglas en inglés), es un estándar internacional que formaliza la publicación de datos de contrataciones de manera accesible y estructurada en las cuatro fases que incluye el proceso de contratación: 

Planeación: En esta fase, el gobierno define un presupuesto de acuerdo a las necesidades que debe cubrir ya sean bienes o servicios.
Licitación: se establecen las necesidades del gobierno por medio de una convocatoria. En función de ésta, las empresas se acercarán con sus propuestas para ofertar al gobierno.
Adjudicación: Una vez que el gobierno ha considerado ya todas las ofertas y ha analizado los pro y los contra, se toma una decisión y se anuncia al proveedor asignado para el contrato.
Contratación: Con la decisión tomada, el gobierno firma un contrato donde se establecen las particularidades del bien o servicio y se fijan los periodos de pago y entrega. 
Implementación o seguimiento al contrato: Durante este paso, es responsabilidad del gobierno dar seguimiento de la entrega y funcionalidad del bien o servicio que contrató. Así como hacer los pagos correspondientes por ese bien o servicio.

Todas estas fases conforman el proceso de contratación del OCDS, el cual está implementado actualmente para la Secretaría de Finanzas y muestra información a partir de la implementación del estándar en  2015.

PROCESO PARA CONTRATAR UN BIEN O SERVICIO
Procedimiento administrativo por el que el Gobierno adquiere o renta bienes y servicios. Los métodos de contratación o adquisición según la Ley, son los siguientes:
Licitación pública (Abierta): Se publica una convocatoria en la Gaceta Oficial de la Ciudad de México (http://www.consejeria.df.gob.mx/index.php/gaceta) y otros medios electrónicos según el caso para una contratación de algún servicio, adquisición o arrendamiento, para que libremente los proveedores presenten propuestas con el fin de asegurar al Gobierno las mejores condiciones en el aspecto administrativo, legal, técnico y económico.
Invitación restringida a cuando menos tres proveedores (Limitada): Cuando la licitación pública no sea idónea para asegurar a la Administración Pública de la CDMX las mejores condiciones disponibles, se podrán contratar adquisiciones, arrendamientos y servicios a través de un procedimiento de invitación a cuando menos tres proveedores. En este caso no se publica en la Gaceta Oficial ni en la página de la Institución, sino que se emiten invitaciones a las personas físicas o morales que se estiman por medio de un estudio de mercado tengan los precios más bajos tomando en consideración la calidad y cantidad de los bienes o servicios a contratar. 
Adjudicación directa (Limitada): En caso de no presentarse el mínimo de proposiciones señaladas en un procedimiento de invitación a cuando menos tres personas y se haya declarado desierto el procedimiento de licitación, el titular del área responsable de la contratación en la dependencia o entidad podrá adjudicar directamente el contrato siempre que no se modifiquen los requisitos establecidos en dichas invitaciones o en las bases de licitación. Esto se encuentra descrito en la Ley de Adquisiciones para el Distrito Federal en el artículo 55.
Convenio de colaboración (Selectiva): Existen instituciones de Gobierno que ya ofrecen el servicio que se está buscando y por ello se debe acudir a ésta. Esto lo establece el artículo primero de la Ley de Adquisiciones para el Distrito Federal. Un ejemplo de esto podría ser la Comisión Mexicana de Impresión (COMISA) o la Policía Bancaria e Industrial (PBI).  
Adjudicación directa selectiva (Selectivo): Esta opción establece que hay proveedores que por tema de marca, patente o derechos de autor, solamente ellos pueden ofrecer el servicio o bien y por lo tanto es necesario recurrir a ellos. Ésta y cualquier otra consideración fuera de una licitación pública, las contempla el artículo 54 en sus diversas fracciones de la Ley de Adquisiciones.

De acuerdo con la Ley de Adquisiciones para el Distrito Federal, todo proceso de contratación debe ser analizado y aprobado por el Comité de Autorizaciones de Adquisiciones, Arrendamientos y Prestación de Servicios de la Administración Pública del Distrito Federal.

El Comité cuenta con Subcomités de Adquisiciones, Arrendamientos y Prestación de Servicios en cada una de las dependencias, órganos desconcentrados y entidades del Gobierno de la Ciudad de México que se encargan de representar al Comité en cada uno de estos entes.

De igual forma, existen los Comités Delegacionales que tienen autonomía funcional del Comité y se rigen por el Reglamento de la Ley de Adquisiciones para el Distrito Federal. Sin embargo, sus funciones y atribuciones están encaminadas al mismo fin que las del Comité.

Para más información puedes consultar la Ley de Adquisiciones para el Distrito Federal (http://www.aldf.gob.mx/archivo-b23bfec910d4dd4b6b1f1fff8ab0e453.pdf) y el Reglamento de la Ley de Adquisiciones para el Distrito Federal (http://www.consejeria.cdmx.gob.mx/images/leyes/reglamentos/REGLAMENTODELALEYDEADQUISICIONESPARAELDISTRITOFEDERALII.pdf).

CRITERIOS DE ADJUDICACIÓN
Este es un proceso de análisis mediante el cual se determinará la adjudicación del bien o servicio que deben cumplir con las mejores condiciones para el Gobierno en el aspecto administrativo, legal, técnico y económico. La CDMX determina mediante dos criterios:
Mejor valor para el gobierno: Este término implica que posterior al análisis una propuesta sobresale en cuanto a que oferta las mejores condiciones en los cuatro aspectos anteriormente mencionados.
Solo hay un participante: En este rubro recaen aquellas opciones que se contienen en el artículo 1o, 54 y 55 de la Ley de Adquisiciones. Es decir, adjudicación directa, adjudicación directa limitada y convenio de colaboración. 

SUFICIENCIA PRESUPUESTAL
 Provisión de recursos para cubrir los requerimientos de remuneración de servicios personales para la adquisición de bienes y la contratación de servicios. Dictado por el Artículo 28 de la Ley de Adquisiciones.

TIPOS DE CONTRATOS SEGÚN EL MONTO ADJUDICADO
Te encontrarás con  varios formatos de contratos en este portal y esto se debe a que el tipo de contrato se rige por el monto adjudicado, todos tienen la misma formalidad y están aprobados por la Consejería Jurídica y de Servicios Legales (CEJUR). Estos se encuentran en el punto 4.7 de la Circular 1 (http://www.om.cdmx.gob.mx/circularuno_unobis/circularunoyunobis.pdf) publicada en la Gaceta Oficial.
Facturas debidamente requisitada: Este formato se utiliza cuando el monto a contratar es menor a 50 mil pesos.
Contrato Pedido: Son aquellos contratos realizados por montos entre 50,001 pesos hasta 200,000 pesos.
Contrato Tipo: Este se efectúa cuando el monto rebasa los 200,001 pesos.
Contrato Multianual: Puede tener cualquiera de los formatos anteriores por el monto, sin embargo este se caracteriza por el tiempo en el que se ejerce ya que abarca más de un ejercicio fiscal.

ARCHIVOS .JSON
Formato para el intercambio de datos, alternativa al formato XML. Una de sus ventajas es que puede ser leído por cualquier lenguaje de programación. Si descargas estos archivos podrás ver a detalle en qué fase va una contratación, así como sus documentos correspondientes.

Para más información sobre los términos que usa el Estándar dentro de los archivos .json puedes descargar este documento: Catálogo de elementos.pdf (https://docs.google.com/document/d/1B9Quoo23vhephvbwdvnpO3E2Wuw-mHYDAhsTzj3Pxbw/edit?usp=sharing)

**Comment by acastedom** [comment]
[Catalogo_Elementos_OCDS.docx.pdf](https://github.com/GobiernoFacil/the-gummy-bears/files/294528/Catalogo_Elementos_OCDS.docx.pdf)

**Comment by hugovom** [comment]
@acastedom cambió todo? en caso contrario, podrían marcar en el drive los cambios?
