### ISSUE TITLE
Duda: No queda claro qué hace la API de Licitaciones. ¿Cuál es la diferencia con la de contratos?

### ISSUE THREAD

**Issue by acastedom** [GobiernoFacil/the-gummy-bears#54]
Duda: No queda claro qué hace la API de Licitaciones. ¿Cuál es la diferencia con la de contratos?

![image](https://cloud.githubusercontent.com/assets/19691136/15719179/6471e9dc-27f4-11e6-8b7a-1b8b0d427853.png)

**Comment by hugovom** [comment]
@elcoruco :point_up_2:
