### ISSUE TITLE
Duda: En pestaña “Proveedores”, ¿qué significa “Licitaciones: 0, Adjudicaciones: 1”? (marcado en recuadro rojo)

### ISSUE THREAD

**Issue by acastedom** [GobiernoFacil/the-gummy-bears#55]
![image](https://cloud.githubusercontent.com/assets/19691136/15719201/7ce0f08a-27f4-11e6-8710-df148d79c625.png)

**Comment by hugovom** [comment]
@acastedom las licitaciones en las que el proveedor ha participado y las adjudicaciones. En el caso de este proveedor Alberto iba a revisar los datos para encontrar por qué tenía adjudicación sin licitación
