### ISSUE TITLE
Duda y posible cambio: ¿Qué significan este elemento? en pestaña “Contratos”, segundo scroll, en cualquier contrato de la lista. (marcado en recuadro rojo

### ISSUE THREAD

**Issue by acastedom** [GobiernoFacil/the-gummy-bears#56]
¿Puede ser el tiempo desde fecha de “licitación” hasta “firma del contrato”?

![image](https://cloud.githubusercontent.com/assets/19691136/15719220/91f6d71e-27f4-11e6-8ad7-e5fcb0735294.png)

**Comment by hugovom** [comment]
@acastedom el tiempo transcurrido desde la licitación
