### ISSUE TITLE
 Cambio: En pestaña “Dependencias”> click “Secretaría de Finanzas”, internamente tenemos un tema con el tipo de cambio y la multianualidad por lo que hasta que quedará resuelto en las próximas dos semanas y afectará lo que se puede visualizar de esta gráfica.  Les pedimos aguantar con esta gráfica hasta que se implemente la multianualidad y el tipo de cambio en el GRP.

### ISSUE THREAD

**Issue by acastedom** [GobiernoFacil/the-gummy-bears#57]
![image](https://cloud.githubusercontent.com/assets/19691136/15719246/afc567c4-27f4-11e6-8eae-2f336fb532c0.png)

Explicación fija a integrarse:

“¿Qué estoy viendo?
El monto total planeado es aquél que se autorizó como suficiencia presupuestal para comenzar el proceso. El monto total adjudicado nos muestra el total que se pagará por el bien o servicio. El monto total contratado nos indica que la cantidad que ya fue formalizada y firmada en un documento llamado contrato. La gráfica de barras muestra una comparación entre los presupuestos dentro de cada fase del proceso.”

**Comment by hugovom** [comment]
@acastedom entonces se oculta la gráfica?

**Comment by acastedom** [comment]
@hugovom Sí Hugo, se oculta por el momento. Cuando haya que modificarlo yo te notifico. Gracias!
