### ISSUE TITLE
Cambio: Quitar los dibujos de las personas y edificios en la pestaña “¿Por qué las contrataciones abiertas?” > segundo scroll. (Se pueden quedar los edificios, o dejar solo el texto, lo que sea más rápido).

### ISSUE THREAD

**Issue by acastedom** [GobiernoFacil/the-gummy-bears#58]
![image](https://cloud.githubusercontent.com/assets/19691136/15719361/37f11418-27f5-11e6-9ab8-08422a99c0f5.png)

**Comment by hugovom** [comment]
@ArgentinaVelasco :point_up_2:

**Comment by ArgentinaVelasco** [comment]
necesitas el escenario sin personas?

**Comment by acastedom** [comment]
Hice una consulta. Me pidieron que se quitara los monitos y los edificios. :(
