### ISSUE TITLE
En DEPENDENCIAS, quitar doble aparición de SEFIN. Sólo debe aparecer una vez

### ISSUE THREAD

**Issue by acastedom** [GobiernoFacil/the-gummy-bears#76]
![image](https://cloud.githubusercontent.com/assets/19691136/17032586/b5a121ac-4f3f-11e6-9671-450364fe0239.png)

**Comment by acastedom** [comment]
Cada dependencia sólo debe aparecer una vez y en esa se debe desglosar toda la información, no pueden aparecer dos o más veces

**Comment by elcoruco** [comment]
<img width="755" alt="screen shot 2016-07-21 at 12 49 14 pm" src="https://cloud.githubusercontent.com/assets/3756555/17032994/99e4b6de-4f41-11e6-851e-0f4103494694.png">

Aquí el detalle es que se genera la dependencia de la combinación de local_id, nombre y uri. Si las tres coinciden, se trata de la misma dependencia, si no, genera una nueva dependencia. 

Entonces, aparecen dos, porque el nombre es el mismo, pero tienen un id distinto: GDF9712054NA para una, y 901 para otra. 

Hay que omologar el id y el nombre de la dependencia, y volver a actualizar los datos.
