### ISSUE TITLE
Contratos, diferencia entre “Contratos” y “Proveedor”

### ISSUE THREAD

**Issue by acastedom** [GobiernoFacil/the-gummy-bears#82]
Revisar query. ¿A qué se debe la diferencia de números?

![ca9](https://cloud.githubusercontent.com/assets/19691136/21411161/d59a0f66-c7ab-11e6-9b7f-bbf0df9a7191.jpg)

**Comment by hugovom** [comment]
- Contratos: Número de contratos en la plataforma
- Proveedores: Número de proveedores con contrato en la plataforma
