### ISSUE TITLE
Dependencias, SEFIN está dos veces

### ISSUE THREAD

**Issue by acastedom** [GobiernoFacil/the-gummy-bears#84]
Encontrar error, ¿por qué se muestra la dirección de SEFIN dos veces?

![ca12](https://cloud.githubusercontent.com/assets/19691136/21411196/2a00f556-c7ac-11e6-9595-1d29aa4aebd6.jpg)

**Comment by hugovom** [comment]
esta es una cuestión de la API de CDMX, es algo que tiene que revisar Alberto en los datos
