### ISSUE TITLE
Dependencia, Redirección web a sitio de SEFIN debe ser actualizado

### ISSUE THREAD

**Issue by acastedom** [GobiernoFacil/the-gummy-bears#85]
Debe redirigir a: http://www.finanzas.cdmx.gob.mx/

![ca13](https://cloud.githubusercontent.com/assets/19691136/21411214/4e9c352e-c7ac-11e6-8663-da85b10b01cc.jpg)

**Comment by hugovom** [comment]
eso también depende de los datos de la API, otro asunto que debe checar Alberto
