### ISSUE TITLE
Contrato individual, etapa licitación. Scroll over con definición en “Método de licitación” y “Criterios de adjudicación”

### ISSUE THREAD

**Issue by acastedom** [GobiernoFacil/the-gummy-bears#91]
Copy Método de Licitación:
-Abierta: A través de la Gaceta Oficial y de medios electrónicos seleccionados, se convoca  a proveedores en general para que libremente se presenten sus propuestas para la contratación de algún servicio.
-Selectiva: Instituciones de Gobierno que ya ofrecen el bien o servicio (a través de un convenio de colaboración) o cuando por marca, patente y/o derechos de autor, solamente hay un proveedor que pueda ofrecer el bien o servicio (adjudicación directa selectiva).
-Limitada: Invitación restringida a cuando menos tres proveedores quienes, posterior a un estudio de mercado, se estime sean las mejores opciones. En caso de no haber tres propuestas se declara desierto el procedimiento y se adjudica de manera directa (adjudicacion directa limitada).

Copy Criterio de Adjudicación:
-Mejor valor para el gobierno: Una propuesta sobresale en el aspecto administrativo, legal, técnico y económico.
-Solo hay un participante: En caso de adjudicación directa, adjudicación directa limitada o convenio de colaboración.

![ca11](https://cloud.githubusercontent.com/assets/19691136/21437384/26c63d4a-c849-11e6-9839-6d2a965caaad.jpg)

**Comment by hugovom** [comment]
esto es un tooltip
