### ISSUE TITLE
Texto de Preguntas frecuentes 

### ISSUE THREAD

**Issue by acastedom** [GobiernoFacil/the-gummy-bears#98]
Cambiar texto en la sección anteriormente conocida como "Términos Clave" a preguntas frecuentes

https://docs.google.com/document/d/1vEQ4Nh-SSSKzd6L_eVEiMa479co8tUvFaR0qK3v0is0/edit#

**Comment by hugovom** [comment]
qué cambió con respecto a esto https://github.com/GobiernoFacil/the-gummy-bears/issues/96 ?
